# Build Docker image and push to repos
name: Docker build and push
on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  image-details:
    runs-on: ubuntu-22.04
    outputs:
      images: ${{ steps.read-json.outputs.images }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - id: read-json
        run: |
          FILE=image_details.json
          if test -f "$FILE"; then
            echo "images=$(jq -c . $FILE)" >> $GITHUB_OUTPUT
          fi

  image_build_push:
    needs: image-details
    name: Build and Push the docker image
    runs-on: ubuntu-22.04
    if: ${{ needs.image-details.outputs.images != '' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.image-details.outputs.images) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: LOGIN TO AWS Public Account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GH_ECR_ROLE }}
          aws-region: us-east-1

      - name: Login to AWS Public ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: BUILD and PUSH DOCKER IMAGE
        env:
          PATH: ${{ matrix.path }}
          REGISTRY: ${{ vars.PUBLIC_ECR }}
          REPOSITORY: ${{ vars.PRODUCT }}/${{ vars.COMPONENT }}/${{ matrix.image_name }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          cd $PATH
          docker ps
